export default {
  url: '/details',
  mock: {
    erroCode: 2000,
    erroMsg: null,
    result: {
      unit5_6: {
        u6_101: {
          stepName: '有关时尚的形容词',
          stepTypeId: 2,
          stepTypeName: '词汇',
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%;">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>时尚形容词</strong><br />\n\t\t\t\t<br />\n\t\t\t\t有许多可用于形容<strong>fashion</strong> 和<strong>clothes</strong> 的形容词。使用它们描述你喜欢的衣服。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/55/98/v/155598/GE_%205.6.2.1.2_r1.mp3</td>\n\t\t\t<td style="width: 20%;">\n\t\t\t\t<em>cool</em></td>\n\t\t\t<td>\n\t\t\t\t酷的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/55/99/v/155599/GE_%205.6.2.1.2_r2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>stylish</em></td>\n\t\t\t<td>\n\t\t\t\t时髦的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/00/v/155600/GE_%205.6.2.1.2_r3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>in style</em></td>\n\t\t\t<td>\n\t\t\t\t时髦</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/01/v/155601/GE_%205.6.2.1.2_r4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>fashionable</em></td>\n\t\t\t<td>\n\t\t\t\t时髦的，流行的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<br />\n\t\t\t\t使用下列形容词，描述你不喜欢的衣服。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/02/v/155602/GE_%205.6.2.1.2_r5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>out of style</em></td>\n\t\t\t<td>\n\t\t\t\t过时的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/03/v/155603/GE_%205.6.2.1.2_r6.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>dreadful</em></td>\n\t\t\t<td>\n\t\t\t\t糟糕的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/04/v/155604/GE_%205.6.2.1.2_r7.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>unfashionable</em></td>\n\t\t\t<td>\n\t\t\t\t旧式的，不时髦的</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<br />',
            layoutType: 'Table'
          }, {
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%;">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t学习新的形容词时，同时学习它的反义词是一种好的方法。以下是服装语境中的一些例子。<br />\n\t\t\t\t<br />\n\t\t\t\t针对很长时间一直都非常时髦的某物，使用<strong>classic</strong>。如果只是一时的时尚，则用<strong>trendy</strong>。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/06/v/155606/GE_%205.6.2.1.2_r8.mp3</td>\n\t\t\t<td style="width: 20%;">\n\t\t\t\t<em>classic - trendy </em></td>\n\t\t\t<td>\n\t\t\t\t经典的 - 时髦的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t&nbsp;<br />\n\t\t\t\t形容衣服有多合身，使用形容词<strong>loose</strong> 和<strong>tight</strong>。注意，</strong>loose</strong> 与<strong>baggy</strong> 意义相近。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/07/v/155607/GE_%205.6.2.1.2_r9.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>loose - tight</em></td>\n\t\t\t<td>\n\t\t\t\t宽松的 - 紧贴的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<br />\n\t\t\t\t形容设计仿造某种材料或品牌、但实际上不是的衣服，使用形容词<strong>fake</strong>。该词常用于修饰并非来自动物的<strong>fur</strong>。如果一件衣服是正品，使用形容词<strong>real</strong>。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/08/v/155608/GE_%205.6.2.1.2_r10.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>fake - real</em></td>\n\t\t\t<td>\n\t\t\t\t伪造的 - 非伪造的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<br />\n\t\t\t\t形容特殊场合穿着的衣服，比如婚礼或工作面试，使用<strong>formal</strong>。使用形容词<strong>casual</strong> 形容日常服装。注意，在该语境中，两个形容词<strong>casual</strong> 和<strong>informal</strong> 意思极为相近。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/15/56/09/v/155609/GE_%205.6.2.1.2_r11.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>formal - casual</em></td>\n\t\t\t<td>\n\t\t\t\t正式的 – 休闲的</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<br />',
            layoutType: 'Table'
          }]
        },
        u6_102: {
          stepName: '动词短语',
          grammarVideo: {
            videoUrl: {
              url: 'https://cns2.ef-cdn.com/Juno/12/62/22/v/126222/GE_5.6.2.2.1.mp4',
              maxAge: 3600,
              collapsed: false,
              id: 'media!126222'
            },
            audioUrl: {
              url: 'https://cns2.ef-cdn.com/Juno/12/62/33/v/126233/GE_5.6.2.2.1_v2.mp3',
              maxAge: 3600,
              collapsed: false,
              id: 'media!126233'
            },
          },
          presentations: [{
            text: '<p>\n\t<strong>动词短语</strong></p>\n<table border="0" cellpadding="0" cellspacing="0" style="width: 100%;" width="680">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t有些动词由两至三个词组成。有的 multiword verbs 可用句子宾语分隔，有的不能。<br />\n\t\t\t\t请看下列不可分隔多词动词的例子。注意，在句中使用时，动词中的所有词必须放在一起。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>https://cns2.ef-cdn.com/Juno/11/17/88/v/111788/GE_5.6.2.2.2_1_v2.mp3</em></td>\n\t\t\t<td>\n\t\t\t\t<em>Let&#39;s <strong>look for</strong> some classic jeans.</em></td>\n\t\t\t<td>\n\t\t\t\t我们找几条经典牛仔裤。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>https://cns2.ef-cdn.com/Juno/11/17/89/v/111789/GE_5.6.2.2.2_2_v2.mp3</em></td>\n\t\t\t<td>\n\t\t\t\t<em>I can&#39;t <strong>keep up with</strong> the trends.</em></td>\n\t\t\t<td>\n\t\t\t\t我跟不上潮流。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t下列多词动词可以分隔。注意，动词中的单词既能在一起，也可用句子宾语分隔。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/11/17/90/v/111790/GE_5.6.2.2.2_3_v2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>I <strong>put on</strong> my tie. </em></td>\n\t\t\t<td>\n\t\t\t\t我戴上领带。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/11/17/91/v/111791/GE_5.6.2.2.2_4_v2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>I <strong>put </strong>my tie <strong>on</strong>.</em></td>\n\t\t\t<td>\n\t\t\t\t我戴上领带。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/11/17/92/v/111792/GE_5.6.2.2.2_5_v2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>I <strong>tried on</strong> 14 baseball caps. </em></td>\n\t\t\t<td>\n\t\t\t\t我试戴了 14 顶棒球帽。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/11/17/87/v/111787/GE_5.6.2.2.2_6_v2.mp3</td>\n\t\t\t<td style="width: 30%;">\n\t\t\t\t<em>I <strong>tried</strong> 14 baseball caps <strong>on</strong>.</em></td>\n\t\t\t<td>\n\t\t\t\t我试戴了 14 顶棒球帽。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<br />',
            layoutType: 'Table'
          }]
        },
        u6_103: {
          stepName: '表达偏爱',
          stepTypeId: 12,
          stepTypeName: '表达',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: "<table border=\"0\" cellpadding=\"1\" cellspacing=\"1\" style=\"width: 100%\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t<strong>关于偏爱的问题</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t您可以使用动词<strong>prefer</strong> 询问某人的偏爱。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/31/v/177931/MOB_5.6.1.4.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>What would you <strong>prefer</strong>?</em></td>\n\t\t\t<td>\n\t\t\t\t您更喜欢什么？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t回答问题，表明您的偏爱。注意，</strong>I</strong> 和<strong>would</strong> 缩写为<strong>I'd</strong>。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"1\" rowspan=\"2\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/32/v/177932/MOB_5.6.1.4.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: What would you <strong>prefer</strong>?</em></td>\n\t\t\t<td>\n\t\t\t\t您更喜欢什么？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: <strong>I&#39;d prefer </strong>something colorful.</em></td>\n\t\t\t<td>\n\t\t\t\t我更喜欢鲜艳的衣服。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t和店员对话时，您可能也会听到动词<strong>prefer</strong>。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td rowspan=\"3\" style=\"width: 5%;\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/33/v/177933/MOB_5.6.1.4.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: I&#39;d like to change these pants, please.</em></td>\n\t\t\t<td>\n\t\t\t\t我想换这条裤子，谢谢。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: Would you <strong>prefer</strong> something more modern?</em></td>\n\t\t\t<td>\n\t\t\t\t您喜欢更现代的衣服吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style=\"width: 45%;\">\n\t\t\t\t<em>A: Yes, please.</em></td>\n\t\t\t<td>\n\t\t\t\t是的，谢谢。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>",
            layoutType: 'Table'
          }, {
            text: "<table border=\"0\" cellpadding=\"1\" cellspacing=\"1\" style=\"width: 100%\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t<strong>表明您的偏爱</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t您也可以表示相比其他某物您更喜欢什么。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/34/v/177934/MOB_5.6.1.4.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>I <strong>prefer</strong> jeans <strong>to</strong> trousers.</em></td>\n\t\t\t<td>\n\t\t\t\t我喜欢牛仔裤而不是裤子。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t如果您对某物不满意，您可以表达您的看法和偏爱。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/35/v/177935/MOB_5.6.1.4.1_5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>It&#39;s too formal. <strong>I&#39;d prefer</strong> something more casual.</em></td>\n\t\t\t<td>\n\t\t\t\t这太正式了，我喜欢更休闲一点的。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t另一种表达偏爱的方法是使用<strong>would rather</strong>。注意其缩写也是<strong>I'd</strong>。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/36/v/177936/MOB_5.6.1.4.1_6.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em><strong>I&#39;d rather</strong> try on something more casual.</em></td>\n\t\t\t<td>\n\t\t\t\t我宁愿穿更休闲的衣服。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t您也可以使用<strong>than</strong> 搭配<strong>rather</strong>，表达您更喜欢的东西。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style=\"width: 5%;\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/37/v/177937/MOB_5.6.1.4.1_7.mp3</td>\n\t\t\t<td style=\"width: 45%;\">\n\t\t\t\t<em><strong>I&#39;d rather</strong> wear something more casual <strong>than</strong> formal to the party.</em></td>\n\t\t\t<td>\n\t\t\t\t我宁愿穿更休闲一点的服装，而不是正式服装去参加聚会。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>",
            layoutType: 'Table'
          }]
        },
        u6_104: {
          stepName: '决定',
          stepTypeName: '表达',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>您定下来了吗？</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您试图在店内做决定，店员可能问您类似这样的问题：</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/48/v/177948/MOB_5.6.1.6.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>Have you decided yet?</em></td>\n\t\t\t<td>\n\t\t\t\t您定下来了吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/49/v/177949/MOB_5.6.1.6.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>Have you found something you like?</em></td>\n\t\t\t<td>\n\t\t\t\t您找到您喜欢的了吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>表明您的决定</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您立刻做出了决定，您可以使用<strong>will +</strong> 动词原形。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/50/v/177950/MOB_5.6.1.6.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>Yeah, I&#39;ll <strong>take</strong> this one.</em></td>\n\t\t\t<td>\n\t\t\t\t是的，我拿这件。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/51/v/177951/MOB_5.6.1.6.1_4.mp3</td>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>Hmmm. <strong>I&#39;ll go for</strong> the blue shirt.</em></td>\n\t\t\t<td>\n\t\t\t\t嗯，我要这件蓝色衬衫。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }, {
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您在被问之前就做好了决定，您可以使用现在完成时：</strong>have +</strong> 过去分词。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/52/v/177952/MOB_5.6.1.6.1_5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>Sure.&nbsp;<strong>I&#39;ve decided</strong>&nbsp;on these.</em></td>\n\t\t\t<td>\n\t\t\t\t当然，我决定要这些。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/53/v/177953/MOB_5.6.1.6.1_6.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>Yes,&nbsp;<strong>I&#39;ve gone for&nbsp;</strong>the black shoes.</em></td>\n\t\t\t<td>\n\t\t\t\t是的，我就要这双黑色鞋子。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您决定不买某物，您可以给出否定的回答。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/54/v/177954/MOB_5.6.1.6.1_7.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>No,&nbsp;<strong>I&#39;ve decided I don&#39;t want</strong>&nbsp;it.</em></td>\n\t\t\t<td>\n\t\t\t\t不了，我决定不想要了。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/55/v/177955/MOB_5.6.1.6.1_8.mp3</td>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>Hmm.&nbsp;<strong>I think I&#39;ll leave</strong>&nbsp;it.</em></td>\n\t\t\t<td>\n\t\t\t\t嗯，我想还是不要了。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }]
        },
        u6_203: {
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>修饰形容词</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您想修饰一个描述的程度，您可以使用副词<strong>+</strong> 形容词，或者副词短语<strong>+</strong> 形容词。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/77/v/177977/MOB_5.6.2.3.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>It&#39;s <strong>really colorful</strong>.</em></td>\n\t\t\t<td>\n\t\t\t\t这十分鲜艳。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/78/v/177978/MOB_5.6.2.3.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>The pants are <strong>a little casual</strong>.</em></td>\n\t\t\t<td>\n\t\t\t\t这条裤子有点休闲。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>降低形容词程度</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您可以使用类似这样的副词短语来降低形容词的程度：</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/79/v/177979/MOB_5.6.2.3.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>It&#39;s <strong>a little too</strong> formal.</em></td>\n\t\t\t<td>\n\t\t\t\t这有点太正式了。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/80/v/177980/MOB_5.6.2.3.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>They&#39;re <strong>a bit </strong>old-fashioned.</em></td>\n\t\t\t<td>\n\t\t\t\t它们有点过时。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/81/v/177981/MOB_5.6.2.3.1_5.mp3</td>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>It&#39;s <strong>a little bit </strong>boring.</em></td>\n\t\t\t<td>\n\t\t\t\t这有点单调。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }, {
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>加强形容词程度</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您也可以使用副词加强形容词的程度。注意，</strong>pretty</strong> 的强度不如<strong>really</strong> 或<strong>so</strong>。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/82/v/177982/MOB_5.6.2.3.1_6.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>It&#39;s <strong>really</strong> colorful.</em></td>\n\t\t\t<td>\n\t\t\t\t这十分鲜艳。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/83/v/177983/MOB_5.6.2.3.1_7.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>They&#39;re <strong>so</strong> modern.</em></td>\n\t\t\t<td>\n\t\t\t\t它们非常现代。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/84/v/177984/MOB_5.6.2.3.1_8.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>These shoes are <strong>pretty</strong> fashionable.</em></td>\n\t\t\t<td>\n\t\t\t\t这双鞋很时髦。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您在批评某事或强调您对批评的回答时可以使用这些副词。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td rowspan="2" style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/85/v/177985/MOB_5.6.2.3.1_9.mp3</td>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>A: I&#39;m not sure I like it&nbsp;</em>&ndash;<em>&nbsp;it&#39;s <strong>really plain</strong>.</em></td>\n\t\t\t<td>\n\t\t\t\t我不确定我喜不喜欢这个，这十分普通。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: But it&#39;s <strong>so modern</strong>, and I like the design.</em></td>\n\t\t\t<td>\n\t\t\t\t但是这非常现代，我喜欢这种设计。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }]
        },
        u6_301: {
          stepName: '修饰衣服的形容词',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>衣服的特性</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t描述衣服特性的形容词有很多，比如它们的用途或穿着的感受。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/95/v/177995/MOB_5.6.3.1.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>comfortable</em></td>\n\t\t\t<td>\n\t\t\t\t舒服的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/96/v/177996/MOB_5.6.3.1.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>sporty</em></td>\n\t\t\t<td>\n\t\t\t\t运动式，运动感</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/97/v/177997/MOB_5.6.3.1.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>waterproof</em></td>\n\t\t\t<td>\n\t\t\t\t防水的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您可以使用形容词谈论材质的重量或风格怎样符合您的偏爱的。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/98/v/177998/MOB_5.6.3.1.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>warm - cool</em></td>\n\t\t\t<td>\n\t\t\t\t温暖的 – 凉爽的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/79/99/v/177999/MOB_5.6.3.1.1_5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>light - heavy</em></td>\n\t\t\t<td>\n\t\t\t\t轻盈的 – 重的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/00/v/178000/MOB_5.6.3.1.1_6.mp3</td>\n\t\t\t<td style="width: 25%;">\n\t\t\t\t<em>loose-fitting - tight&nbsp;</em></td>\n\t\t\t<td>\n\t\t\t\t宽松的 – 紧身的</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }]
        },
        u6_303: {
          stepName: '建议与义务',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>询问建议</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您想就某事咨询建议，您可以用<strong>should</strong> 提问。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/02/v/178002/MOB_5.6.3.3.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>What <strong>should</strong> I wear tonight?</em></td>\n\t\t\t<td>\n\t\t\t\t我今晚应该穿什么？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/03/v/178003/MOB_5.6.3.3.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em><strong>Should</strong> I take some warm clothes?</em></td>\n\t\t\t<td>\n\t\t\t\t我该带点暖和的衣服吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t这些问题的回答通常是一种观点。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>询问要求</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t相比询问建议，如果您觉得某场合或活动可能具有某种义务，您可以使用<strong>have to</strong> 提问。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td rowspan="2" style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/04/v/178004/MOB_5.6.3.3.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>Do I have to</strong> wear something smart?</em></td>\n\t\t\t<td>\n\t\t\t\t我必须穿讲究一点吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>B: Yes, it&#39;s a formal dress code.</em></td>\n\t\t\t<td>\n\t\t\t\t是的，着装要求必须正式。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }, {
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您想询问某件必要但非必须的事，那就是用<strong>need to</strong> 提问。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="1" rowspan="2">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/05/v/178005/MOB_5.6.3.3.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: Do I <strong>need to</strong> take a waterproof jacket?</em></td>\n\t\t\t<td>\n\t\t\t\t我需要带一件防水外套吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: Yes, I think it&#39;s going to rain tomorrow.</em></td>\n\t\t\t<td>\n\t\t\t\t是的，我觉得明天会下雨。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您也可以使用<strong>Would</strong> + 主语 +<strong>be OK</strong> 来询问一个场合。回答表明一种义务、需要或建议。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="1" rowspan="2">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/06/v/178006/MOB_5.6.3.3.1_5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>Would I be OK</strong> wearing a T-shirt and jeans?</em></td>\n\t\t\t<td>\n\t\t\t\t我穿 T 恤和牛仔裤行吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: No. It&#39;s a formal dinner. You have to wear a suit!</em></td>\n\t\t\t<td>\n\t\t\t\t不行。这是正式宴会。你必须穿西装！</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td rowspan="2" style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/07/v/178007/MOB_5.6.3.3.1_6.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>Would we be OK</strong> without an umbrella?</em></td>\n\t\t\t<td>\n\t\t\t\t我们不带伞行吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>B: Yes. I don&#39;t think we need one.</em></td>\n\t\t\t<td>\n\t\t\t\t行的，我觉得用不着伞。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }]
        },
        u6_401: {
          stepName: '了不起的形容词',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 837px">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>表示某物很好的形容词</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t如果您想描述某物您觉得很不错，则可以使用类似这就样的形容词。它们可用于修饰人或物，甚至想法。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5px;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/15/v/178015/MOB_5.6.4.1.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>fantastic</em></td>\n\t\t\t<td>\n\t\t\t\t极好的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/16/v/178016/MOB_5.6.4.1.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>amazing</em></td>\n\t\t\t<td>\n\t\t\t\t令人吃惊的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/17/v/178017/MOB_5.6.4.1.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>incredible</em></td>\n\t\t\t<td>\n\t\t\t\t不可思议的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/18/v/178018/MOB_5.6.4.1.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>wonderful</em></td>\n\t\t\t<td>\n\t\t\t\t出色的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }, {
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 837px">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>表示某物漂亮的形容词</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您也可以使用形容词描述漂亮的人或物。**Pretty** 通常用于形容女性，**handsome** 则用于形容男性。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5px;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/19/v/178019/MOB_5.6.4.1.1_5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>handsome</em></td>\n\t\t\t<td>\n\t\t\t\t英俊的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/20/v/178020/MOB_5.6.4.1.1_6.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>pretty</em></td>\n\t\t\t<td>\n\t\t\t\t美丽的</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/80/21/v/178021/MOB_5.6.4.1.1_7.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>gorgeous</em></td>\n\t\t\t<td>\n\t\t\t\t非常漂亮的</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }]
        },
        u6_402: {
          stepName: '赞美',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>给予赞美</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t用**look +**形容词来恭维某人的外貌。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/89/v/177089/MOB_5.6.4.3.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<div>\n\t\t\t\t\t<em>You <strong>look fantastic</strong>!</em></div>\n\t\t\t</td>\n\t\t\t<td>\n\t\t\t\t你看起来很美！</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/88/v/177088/MOB_5.6.4.3.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>That shirt <strong>looks great </strong>on you.</em></td>\n\t\t\t<td>\n\t\t\t\t你穿那件衬衫很好看。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/87/v/177087/MOB_5.6.4.3.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>That color <strong>looks good</strong> with your hair.</em></td>\n\t\t\t<td>\n\t\t\t\t那个颜色和你的发色很配。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t您也可以用**good at +**动词 **+ ing** 来恭维他人。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/86/v/177086/MOB_5.6.4.3.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>You&#39;re <strong>good at putting together</strong> an outfit.</em></td>\n\t\t\t<td>\n\t\t\t\t你很擅长搭配衣服。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/85/v/177085/MOB_5.6.4.3.1_5.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>You&#39;re <strong>great at creating</strong> new styles.</em></td>\n\t\t\t<td>\n\t\t\t\t你很擅长创造新的风格。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t赞美别人的另一种方式是夸张。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/84/v/177084/MOB_5.6.4.3.1_6.mp3</td>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t<em>You&#39;re 35 years old? You look 29!</em></td>\n\t\t\t<td>\n\t\t\t\t你 35 岁吗？你看起来像 29 岁！</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }, {
            text: '<table border="0" cellpadding="1" cellspacing="1" style="width: 100%">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t<strong>获得赞美</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t要得到恭维，用**like**提问。\r\n \r\n\r\n\r\n</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="1" rowspan="2">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/83/v/177083/MOB_5.6.4.3.1_7.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>Do you like</strong> my outfit?</em></td>\n\t\t\t<td>\n\t\t\t\t你喜欢我的衣服吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: Absolutely. You know clothes better than anyone!</em></td>\n\t\t\t<td>\n\t\t\t\t当然喜欢。你比任何人都懂衣服。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="1" rowspan="2">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/90/v/177090/MOB_5.6.4.3.1_8.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: How <strong>do you like</strong> my hair?</em></td>\n\t\t\t<td>\n\t\t\t\t你觉得我的头发怎么样？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: It looks gorgeous!</em></td>\n\t\t\t<td>\n\t\t\t\t看起来非常漂亮！</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style="width: 5%;">\n\t\t\t\t&nbsp;</td>\n\t\t\t<td style="width: 35%;">\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan="3">\n\t\t\t\t注意：频繁要人赞美你，可能会让人产生厌烦，或给人感觉自我。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>',
            layoutType: 'Table'
          }]
        },
        u6_403: {
          stepName: '保证',
          grammarVideo: {
            scripts: []
          },
          presentations: [{
            text: "<table border=\"0\" cellpadding=\"1\" cellspacing=\"1\" style=\"width: 100%\">\n\t<tbody>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t<strong>寻求和给予安慰</strong></td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t如果您对您的外表有疑问，用**I'm not sure about**来确认，告诉别人不要担心以消除疑虑，然后说上一句恭维。 \r\n</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"1\" rowspan=\"2\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/95/v/177095/MOB_5.6.4.5.1_1.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>I&#39;m not sure about</strong> this tie.</em></td>\n\t\t\t<td>\n\t\t\t\t我不确定这条领带是否合适。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: I wouldn&#39;t worry about it. The color looks good with your suit.</em></td>\n\t\t\t<td>\n\t\t\t\t要我就不担心。这个颜色和你的西服很配。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"1\" rowspan=\"2\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/94/v/177094/MOB_5.6.4.5.1_2.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em><strong>A: I&#39;m not sure about</strong> my outfit.</em></td>\n\t\t\t<td>\n\t\t\t\t我不确定我的衣服打扮好不好。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: Don&#39;t worry. You look great!</em></td>\n\t\t\t<td>\n\t\t\t\t别担心。你看起来很棒！</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"3\">\n\t\t\t\t您也可以用带有**think** 的问题来请求确认，说 **not at all** 或**Actually, no.**来消除疑虑。您也可以告诉他们不要担心，并加一句恭维。</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td colspan=\"1\" rowspan=\"2\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/93/v/177093/MOB_5.6.4.5.1_3.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>Do you think</strong> this outfit makes me look ugly?</em></td>\n\t\t\t<td>\n\t\t\t\t你觉得我这一套衣服看起来难看吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t<em>B: Not at all!</em></td>\n\t\t\t<td>\n\t\t\t\t一点也不！</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t\t<td>\n\t\t\t\t&nbsp;</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td rowspan=\"2\" style=\"width: 5%;\">\n\t\t\t\thttps://cns2.ef-cdn.com/Juno/17/70/96/v/177096/MOB_5.6.4.5.1_4.mp3</td>\n\t\t\t<td>\n\t\t\t\t<em>A: <strong>You don&#39;t think</strong> this necklace is weird?</em></td>\n\t\t\t<td>\n\t\t\t\t你不觉得这条项链很怪吗？</td>\n\t\t</tr>\n\t\t<tr>\n\t\t\t<td style=\"width: 35%;\">\n\t\t\t\t<em>B: Actually, no. Don&#39;t worry&nbsp;</em>&ndash;<em>&nbsp;you look fabulous.</em></td>\n\t\t\t<td>\n\t\t\t\t实际上不是。别担心，你看起来很美。</td>\n\t\t</tr>\n\t</tbody>\n</table>\n<p>\n\t&nbsp;</p>",
            layoutType: 'Table'
          }]
        }
      },
    },
  }
};

